### ISSUE TITLE
MVP Tracking Ticket

### ISSUE THREAD

**Issue by knowtheory** [knowtheory/audience-mapper#15]
This is a ticket to keep track of the current list and priority order of items to be accomplished.

- [ ] [Navigational UX issues](https://github.com/knowtheory/audience-mapper/issues/12)
- [ ] [Demo/Live toggle on Followup Page](https://github.com/knowtheory/audience-mapper/issues/13)
- [ ] [Confirmation dialogs & actually tweeting results](https://github.com/knowtheory/audience-mapper/issues/13)
- [ ] [Updating/Fetching more results on existing subjects](https://github.com/knowtheory/audience-mapper/issues/4)
